In [1]:
import numpy as np
import polars as pl

In [2]:
augs = pl.scan_csv("augmenter_setups_3.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Destruction"),
    ~pl.col("").str.contains("Art of Fast Killing"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Healing"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()

In [3]:
augs = augs.with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength"))))),
    dph=(100 * (1 + pl.col("Damage"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [4]:
a1 = '''"Qa'ik Urk'qii Akk'oj"'''
a2 = "'Raurava Bhava'"
a3 = "'Celeste Mark Augmenter'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a2}, {a3}")
)

shape: (1, 32)
┌──────────┬──────────┬────────────────┬───────────────┬───┬─────────┬────────┬────────────┬───────┐
│          ┆ Capacity ┆ Critical Hit   ┆ Critical Hit  ┆ … ┆ Weapons ┆ Weight ┆ dps        ┆ dph   │
│ ---      ┆ ---      ┆ Chance         ┆ Strength      ┆   ┆ Slots   ┆ ---    ┆ ---        ┆ ---   │
│ str      ┆ f64      ┆ ---            ┆ ---           ┆   ┆ ---     ┆ f64    ┆ f64        ┆ f64   │
│          ┆          ┆ f64            ┆ f64           ┆   ┆ f64     ┆        ┆            ┆       │
╞══════════╪══════════╪════════════════╪═══════════════╪═══╪═════════╪════════╪════════════╪═══════╡
│ ("Qa'ik  ┆ 0.0      ┆ 0.2            ┆ 0.9           ┆ … ┆ 0.0     ┆ 0.0    ┆ 389.508197 ┆ 396.0 │
│ Urk'qii  ┆          ┆                ┆               ┆   ┆         ┆        ┆            ┆       │
│ Akk'oj", ┆          ┆                ┆               ┆   ┆         ┆        ┆            ┆       │
│ 'Raur…   ┆          ┆                ┆               ┆   ┆         ┆        ┆            ┆       │
└──────────┴──────────┴────────────────┴───────────────┴───┴─────────┴────────┴────────────┴───────┘

In [5]:
a1 = '''"Qa'ik Urk'qii Akk'oj"'''
a2 = "'Luminous Intersticial Desistance Augmenter'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a1}, {a2}")
)

shape: (1, 32)
┌──────────┬──────────┬───────────────┬───────────────┬───┬───────────────┬────────┬───────┬───────┐
│          ┆ Capacity ┆ Critical Hit  ┆ Critical Hit  ┆ … ┆ Weapons Slots ┆ Weight ┆ dps   ┆ dph   │
│ ---      ┆ ---      ┆ Chance        ┆ Strength      ┆   ┆ ---           ┆ ---    ┆ ---   ┆ ---   │
│ str      ┆ f64      ┆ ---           ┆ ---           ┆   ┆ f64           ┆ f64    ┆ f64   ┆ f64   │
│          ┆          ┆ f64           ┆ f64           ┆   ┆               ┆        ┆       ┆       │
╞══════════╪══════════╪═══════════════╪═══════════════╪═══╪═══════════════╪════════╪═══════╪═══════╡
│ ("Qa'ik  ┆ 0.15     ┆ 0.6           ┆ 2.2           ┆ … ┆ -0.01         ┆ 0.0    ┆ 479.4 ┆ 479.4 │
│ Urk'qii  ┆          ┆               ┆               ┆   ┆               ┆        ┆       ┆       │
│ Akk'oj", ┆          ┆               ┆               ┆   ┆               ┆        ┆       ┆       │
│ "Qa'i…   ┆          ┆               ┆               ┆   ┆               ┆        ┆       ┆       │
└──────────┴──────────┴───────────────┴───────────────┴───┴───────────────┴────────┴───────┴───────┘

In [8]:
tmp = augs.filter(
    # ~pl.col("").str.contains("Luminous"),
    # ~pl.col("").str.contains("Illunis"),
    # ~pl.col("").str.contains("Promontory"),
    # pl.col("Damage") >= 2.0,
    # pl.col("Rate of Fire") >= 0.0,
    pl.col("Shield Max") >= 1.7,
    pl.col("Shield Recovery") >= 1.0,
    pl.col("Resistance to Damage") >= 0.3,
    # pl.col("Electric Tempering") <= -0.1,
    # pl.col("Range") >= 0.25,
    # pl.col("Critical Hit Chance") >= 0.2,
    # pl.col("Critical Hit Strength") >= 0.9,
    # pl.col("Rate of Fire") <= 0.2,
    # pl.col("dps") >= 400,
    pl.col("dph") >= 400
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
)

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=20):
    display(tmp.sort("dph", descending=True))

shape: (4, 21)
┌──────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬─────────┬────────┬────────┬────────┐
│                                                                                                      ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Turning ┆ Weight ┆ dps    ┆ dph    │
│ ---                                                                                                  ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---     ┆ ---    ┆ ---    ┆ ---    │
│ str                                                                                                  ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64     ┆ f64    ┆ f64    ┆ f64    │
╞══════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪═════════╪════════╪════════╪════════╡
│ ("Qa'ik Urk'qii Akk'oj", "Qa'ik Urk'qii Akk'oj", 'Luminous Intersticial Desistance Augmenter')       ┆ 0.15     ┆ 0.6                 ┆ 2.2                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 479.4  ┆ 479.4  │
│ ("Qa'ik Urk'qii Akk'oj", "Qa'ik Urk'qii Akk'oj", 'Raurava Bhava')                                    ┆ 0.0      ┆ 0.4                 ┆ 1.2                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 278.07 ┆ 463.45 │
│ ("Qa'ik Urk'qii Akk'oj", 'Mechanical Hound Augmenter', 'Luminous Intersticial Desistance Augmenter') ┆ 0.15     ┆ 0.4                 ┆ 1.6                   ┆ … ┆ 0.5     ┆ 0.0    ┆ 412.1  ┆ 412.1  │
│ ("Qa'ik Urk'qii Akk'oj", 'Raurava Bhava', 'Mechanical Hound Augmenter')                              ┆ 0.0      ┆ 0.2                 ┆ 0.6                   ┆ … ┆ 0.5     ┆ 0.0    ┆ 241.2  ┆ 402.0  │
└──────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴─────────┴────────┴────────┴────────┘