In [1]:
import numpy as np
import polars as pl

In [2]:
augs = pl.scan_csv("augmenter_setups_3.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max", "Transference Power").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Destruction"),
    ~pl.col("").str.contains("Art of Fast Killing"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Sharpshooting"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()

In [3]:
augs = augs.with_columns(
    hps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Transference Power")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength"))))),
    hph=(100 * (1 + pl.col("Damage"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [9]:
a1 = "'Ultimate Art of Healing Augmenter'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a1}, {a1}")
)

shape: (1, 32)
┌───────────────┬──────────┬───────────────┬──────────┬───┬───────────────┬────────┬───────┬───────┐
│               ┆ Capacity ┆ Critical Hit  ┆ Critical ┆ … ┆ Weapons Slots ┆ Weight ┆ hps   ┆ hph   │
│ ---           ┆ ---      ┆ Chance        ┆ Hit      ┆   ┆ ---           ┆ ---    ┆ ---   ┆ ---   │
│ str           ┆ f64      ┆ ---           ┆ Strength ┆   ┆ f64           ┆ f64    ┆ f64   ┆ f64   │
│               ┆          ┆ f64           ┆ ---      ┆   ┆               ┆        ┆       ┆       │
│               ┆          ┆               ┆ f64      ┆   ┆               ┆        ┆       ┆       │
╞═══════════════╪══════════╪═══════════════╪══════════╪═══╪═══════════════╪════════╪═══════╪═══════╡
│ ('Ultimate    ┆ 0.0      ┆ 0.0           ┆ 0.0      ┆ … ┆ 0.0           ┆ 0.0    ┆ 631.4 ┆ 102.5 │
│ Art of        ┆          ┆               ┆          ┆   ┆               ┆        ┆       ┆       │
│ Healing Augm… ┆          ┆               ┆          ┆   ┆               ┆        ┆       ┆       │
└───────────────┴──────────┴───────────────┴──────────┴───┴───────────────┴────────┴───────┴───────┘

In [14]:
a1 = "'Ultimate Art of Healing Augmenter'"
a2 = "'Vaidya Bhava'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a1}, {a2}")
)

shape: (1, 32)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬────────┬───────────┬──────────┐
│            ┆ Capacity ┆ Critical   ┆ Critical   ┆ … ┆ Weapons    ┆ Weight ┆ hps       ┆ hph      │
│ ---        ┆ ---      ┆ Hit Chance ┆ Hit        ┆   ┆ Slots      ┆ ---    ┆ ---       ┆ ---      │
│ str        ┆ f64      ┆ ---        ┆ Strength   ┆   ┆ ---        ┆ f64    ┆ f64       ┆ f64      │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆        ┆           ┆          │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆        ┆           ┆          │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════╪═══════════╪══════════╡
│ ('Ultimate ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ … ┆ 0.0        ┆ 0.0    ┆ 715.05787 ┆ 139.3875 │
│ Art of     ┆          ┆            ┆            ┆   ┆            ┆        ┆ 5         ┆          │
│ Healing    ┆          ┆            ┆            ┆   ┆            ┆        ┆           ┆          │
│ Augm…      ┆          ┆            ┆            ┆   ┆            ┆        ┆           ┆          │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴────────┴───────────┴──────────┘

In [13]:
tmp = augs.filter(
    # ~pl.col("").str.contains("Luminous"),
    # ~pl.col("").str.contains("Illunis"),
    # ~pl.col("").str.contains("Promontory"),
    # pl.col("Damage") >= 2.0,
    # pl.col("Rate of Fire") >= 0.0,
    pl.col("Shield Max") >= 1.5,
    pl.col("Shield Recovery") >= 2.5,
    pl.col("Resistance to Damage") >= 0.4,
    # pl.col("Electric Tempering") <= -0.1,
    # pl.col("Range") >= 0.25,
    # pl.col("Critical Hit Chance") >= 0.2,
    # pl.col("Critical Hit Strength") >= 0.9,
    # pl.col("Rate of Fire") <= 0.2,
    # pl.col("dps") >= 400,
    pl.col("hps") >= 600
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
)

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=20):
    display(tmp.sort("hps", descending=True))

shape: (12, 21)
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┬─────────────────────┬───────────────────────┬───┬─────────┬────────┬────────────┬──────────┐
│                                                                                                                                  ┆ Capacity  ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Turning ┆ Weight ┆ hps        ┆ hph      │
│ ---                                                                                                                              ┆ ---       ┆ ---                 ┆ ---                   ┆   ┆ ---     ┆ ---    ┆ ---        ┆ ---      │
│ str                                                                                                                              ┆ f64       ┆ f64                 ┆ f64                   ┆   ┆ f64     ┆ f64    ┆ f64        ┆ f64      │
╞══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════╪═════════════════════╪═══════════════════════╪═══╪═════════╪════════╪════════════╪══════════╡
│ ("Nightfury's Patience", "Poseidon's Defensive Mode Augmenter", 'Luminous Munitions Amplifier Augmenter')                        ┆ -0.010989 ┆ 0.0                 ┆ 0.0                   ┆ … ┆ -0.33   ┆ 0.0    ┆ 938.23785  ┆ 206.025  │
│ ("Kidd's Modification", "Poseidon's Defensive Mode Augmenter", 'Mechanical Hound Augmenter')                                     ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.9     ┆ 0.0    ┆ 846.855    ┆ 184.5    │
│ ("Grand Navigator's Augmenter", "Poseidon's Defensive Mode Augmenter", 'Mechanical Hound Augmenter')                             ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.5     ┆ 0.0    ┆ 823.33125  ┆ 230.625  │
│ ("Poseidon's Defensive Mode Augmenter", 'Equinox Shielding Augmenter', 'Luminous Munitions Amplifier Augmenter')                 ┆ 0.1       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 770.8041   ┆ 216.275  │
│ ('Ultimate Art of Healing Augmenter', 'Ultimate Art of Healing Augmenter', 'Vaidya Bhava')                                       ┆ 0.0       ┆ 0.0                 ┆ 0.3                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 715.057875 ┆ 139.3875 │
│ ('Ultimate Art of Healing Augmenter', "Poseidon's Defensive Mode Augmenter", 'Luminous Vitreous Stimulative Augmenter')          ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 702.15985  ┆ 171.175  │
│ ('Ultimate Art of Healing Augmenter', "Poseidon's Defensive Mode Augmenter", 'Glamorous Crepuscularized Potentiality Augmenter') ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 654.36     ┆ 143.5    │
│ ("Poseidon's Defensive Mode Augmenter", 'Vaidya Bhava', 'Luminous Vitreous Stimulative Augmenter')                               ┆ 0.0       ┆ 0.0                 ┆ 0.3                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 649.262845 ┆ 208.565  │
│ ("Grand Navigator's Augmenter", 'Ultimate Art of Healing Augmenter', "Poseidon's Defensive Mode Augmenter")                      ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 642.06     ┆ 148.625  │
│ ('Ultimate Art of Healing Augmenter', 'Ultimate Art of Healing Augmenter', 'Ultimate Art of Healing Augmenter')                  ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 631.4      ┆ 102.5    │
│ ("Qa'ik Urk'qii Akk'oj", 'Ultimate Art of Healing Augmenter', "Poseidon's Defensive Mode Augmenter")                             ┆ 0.0       ┆ 0.2                 ┆ 0.6                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 624.96     ┆ 186.0    │
│ ('Ultimate Art of Healing Augmenter', "Poseidon's Defensive Mode Augmenter", 'Vaidya Bhava')                                     ┆ 0.0       ┆ 0.0                 ┆ 0.3                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 606.335625 ┆ 139.3875 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┴─────────────────────┴───────────────────────┴───┴─────────┴────────┴────────────┴──────────┘