In [1]:
import numpy as np
import polars as pl

In [2]:
augs = pl.scan_csv("augmenter_setups_3.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Destruction"),
    ~pl.col("").str.contains("Art of Fast Killing"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Healing"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()

In [3]:
augs = augs.with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [17]:
a1 = '''"Qa'ik Urk'qii Akk'oj"'''
a2 = "'Raurava Bhava'"
a3 = "'Celeste Mark Augmenter'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a2}, {a3}")
)

shape: (1, 31)
┌──────────┬──────────┬──────────────┬──────────────┬───┬────────┬─────────┬────────┬──────────────┐
│          ┆ Capacity ┆ Critical Hit ┆ Critical Hit ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps          │
│ ---      ┆ ---      ┆ Chance       ┆ Strength     ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---          │
│ str      ┆ f64      ┆ ---          ┆ ---          ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64          │
│          ┆          ┆ f64          ┆ f64          ┆   ┆ f64    ┆ f64     ┆        ┆              │
╞══════════╪══════════╪══════════════╪══════════════╪═══╪════════╪═════════╪════════╪══════════════╡
│ ("Qa'ik  ┆ 0.0      ┆ 0.2          ┆ 0.9          ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 389.508197   │
│ Urk'qii  ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆              │
│ Akk'oj", ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆              │
│ 'Raur…   ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆              │
└──────────┴──────────┴──────────────┴──────────────┴───┴────────┴─────────┴────────┴──────────────┘

In [25]:
tmp = augs.filter(
    ~pl.col("").str.contains("Luminous"),
    ~pl.col("").str.contains("Illunis"),
    ~pl.col("").str.contains("Promontory"),
    # pl.col("Damage") >= 2.0,
    # pl.col("Rate of Fire") >= 0.0,
    pl.col("Shield Max") >= 2.1,
    pl.col("Resistance to Damage") >= 0.4,
    # pl.col("Electric Tempering") <= -0.1,
    pl.col("Range") >= 0.5,
    # pl.col("Critical Hit Chance") >= 0.2,
    # pl.col("Critical Hit Strength") >= 0.6
    pl.col("Rate of Fire") <= 0.25,
    pl.col("dps") >= 400,
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
)

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=20):
    display(tmp.sort("dps", descending=True))

shape: (2, 20)
┌─────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬────────────────────┬─────────┬────────┬────────────┐
│                                                                                             ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Transference Power ┆ Turning ┆ Weight ┆ dps        │
│ ---                                                                                         ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---                ┆ ---     ┆ ---    ┆ ---        │
│ str                                                                                         ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64                ┆ f64     ┆ f64    ┆ f64        │
╞═════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪════════════════════╪═════════╪════════╪════════════╡
│ ('Ultimate Art of Sharpshooting Augmenter', 'Raurava Bhava', 'Celestial Nebulae Augmenter') ┆ 0.0      ┆ 0.3                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0     ┆ 0.0    ┆ 412.816667 │
│ ('Raurava Bhava', 'Celestial Nebulae Augmenter', "Operative's Guided Harmonizer Augmenter") ┆ 0.05     ┆ 0.2                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0     ┆ 0.0    ┆ 405.45     │
└─────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴────────────────────┴─────────┴────────┴────────────┘