In [1]:
import numpy as np
import polars as pl

In [2]:
augs = pl.scan_csv("augmenter_setups_3.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max", "Transference Power").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Destruction"),
    ~pl.col("").str.contains("Art of Fast Killing"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Sharpshooting"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()

In [3]:
augs = augs.with_columns(
    hps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Transference Power")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength"))))),
    hph=(100 * (1 + pl.col("Damage"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [9]:
a1 = "'Ultimate Art of Healing Augmenter'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a1}, {a1}")
)

shape: (1, 32)
┌───────────────┬──────────┬───────────────┬──────────┬───┬───────────────┬────────┬───────┬───────┐
│               ┆ Capacity ┆ Critical Hit  ┆ Critical ┆ … ┆ Weapons Slots ┆ Weight ┆ hps   ┆ hph   │
│ ---           ┆ ---      ┆ Chance        ┆ Hit      ┆   ┆ ---           ┆ ---    ┆ ---   ┆ ---   │
│ str           ┆ f64      ┆ ---           ┆ Strength ┆   ┆ f64           ┆ f64    ┆ f64   ┆ f64   │
│               ┆          ┆ f64           ┆ ---      ┆   ┆               ┆        ┆       ┆       │
│               ┆          ┆               ┆ f64      ┆   ┆               ┆        ┆       ┆       │
╞═══════════════╪══════════╪═══════════════╪══════════╪═══╪═══════════════╪════════╪═══════╪═══════╡
│ ('Ultimate    ┆ 0.0      ┆ 0.0           ┆ 0.0      ┆ … ┆ 0.0           ┆ 0.0    ┆ 631.4 ┆ 102.5 │
│ Art of        ┆          ┆               ┆          ┆   ┆               ┆        ┆       ┆       │
│ Healing Augm… ┆          ┆               ┆          ┆   ┆               ┆        ┆       ┆       │
└───────────────┴──────────┴───────────────┴──────────┴───┴───────────────┴────────┴───────┴───────┘

In [14]:
a1 = "'Ultimate Art of Healing Augmenter'"
a2 = "'Vaidya Bhava'"
augs.filter(
    pl.col("").str.contains(f"{a1}, {a1}, {a2}")
)

shape: (1, 32)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬────────┬───────────┬──────────┐
│            ┆ Capacity ┆ Critical   ┆ Critical   ┆ … ┆ Weapons    ┆ Weight ┆ hps       ┆ hph      │
│ ---        ┆ ---      ┆ Hit Chance ┆ Hit        ┆   ┆ Slots      ┆ ---    ┆ ---       ┆ ---      │
│ str        ┆ f64      ┆ ---        ┆ Strength   ┆   ┆ ---        ┆ f64    ┆ f64       ┆ f64      │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆        ┆           ┆          │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆        ┆           ┆          │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════╪═══════════╪══════════╡
│ ('Ultimate ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ … ┆ 0.0        ┆ 0.0    ┆ 715.05787 ┆ 139.3875 │
│ Art of     ┆          ┆            ┆            ┆   ┆            ┆        ┆ 5         ┆          │
│ Healing    ┆          ┆            ┆            ┆   ┆            ┆        ┆           ┆          │
│ Augm…      ┆          ┆            ┆            ┆   ┆            ┆        ┆           ┆          │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴────────┴───────────┴──────────┘

In [4]:
tmp = augs.filter(
    # ~pl.col("").str.contains("Luminous"),
    # ~pl.col("").str.contains("Illunis"),
    # ~pl.col("").str.contains("Promontory"),
    # pl.col("Damage") >= 0.85,
    # pl.col("Rate of Fire") >= 0.0,
    pl.col("Energy Charge") >= 0.7,
    pl.col("Shield Max") >= 1.0,
    # pl.col("Shield Recovery") >= 2.5,
    pl.col("Resistance to Damage") >= 0.1,
    pl.col("Electric Tempering") <= -0.5,
    pl.col("Range") >= 1.0,
    pl.col("Critical Hit Chance") >= 0.3,
    pl.col("Critical Hit Strength") >= 0.5,
    # pl.col("dps") >= 400,
    pl.col("hps") >= 600
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
)

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=20):
    display(tmp.sort("hps", descending=True))

shape: (2, 21)
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬─────────┬────────┬────────────┬──────────┐
│                                                                                                                ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Turning ┆ Weight ┆ hps        ┆ hph      │
│ ---                                                                                                            ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---     ┆ ---    ┆ ---        ┆ ---      │
│ str                                                                                                            ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64     ┆ f64    ┆ f64        ┆ f64      │
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪═════════╪════════╪════════════╪══════════╡
│ ('Selenite Augmenter', 'Luminous Resplendent Fluxion Augmenter', 'Lustrous Preposterous Fusillade Augmenter')  ┆ 0.13     ┆ 0.3                 ┆ 0.5                   ┆ … ┆ 0.0     ┆ 0.0    ┆ 689.009375 ┆ 233.5625 │
│ ('Selenite Augmenter', 'Lustrous Preposterous Fusillade Augmenter', 'Lustrous Unalloyed Promontory Augmenter') ┆ 0.0      ┆ 0.36                ┆ 0.5                   ┆ … ┆ 0.0     ┆ 2.0    ┆ 661.595    ┆ 287.65   │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴─────────┴────────┴────────────┴──────────┘