In [1]:
import numpy as np
import polars as pl

In [2]:
augs = pl.scan_csv("augmenter_setups_3.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Sharpshooting"),
    ~pl.col("").str.contains("Art of Fast Killing"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Healing"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()

In [4]:
augs = augs.with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [5]:
with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000):
    display(augs.filter(
        # augs[''].str.contains("Art of Destruction Augmenter, Ultimate") & augs[''].str.contains("Zarkara")
        pl.col("").str.contains("Ultimate Art of Destruction Augmenter', 'Ultimate Art of Destruction Augmenter', 'Zarkara")
    ))

shape: (1, 31)
┌──────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬─────────────┬───────────────┬────────┬───────┐
│                                                                                                      ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Weapon Hold ┆ Weapons Slots ┆ Weight ┆ dps   │
│ ---                                                                                                  ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---         ┆ ---           ┆ ---    ┆ ---   │
│ str                                                                                                  ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64         ┆ f64           ┆ f64    ┆ f64   │
╞══════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪═════════════╪═══════════════╪════════╪═══════╡
│ ('Ultimate Art of Destruction Augmenter', 'Ultimate Art of Destruction Augmenter', 'Zarkara Sattva') ┆ 0.0      ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 1.0         ┆ 0.0           ┆ 0.0    ┆ 639.6 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴─────────────┴───────────────┴────────┴───────┘

In [26]:
a1 = "'Selenite Augmenter'"
a2 = '''"Operative's Cosmic Symmetry Augmenter"'''
a3 = '''"Qa'ik Urk'qii Akk'oj"'''

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000):
    display(augs.filter(
        # augs[''].str.contains("Art of Destruction Augmenter, Ultimate") & augs[''].str.contains("Zarkara")
        pl.col("").str.contains(f"{a3}, {a1}, {a2}")
    ))

shape: (1, 31)
┌─────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬─────────────┬───────────────┬────────┬────────────┐
│                                                                                         ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Weapon Hold ┆ Weapons Slots ┆ Weight ┆ dps        │
│ ---                                                                                     ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---         ┆ ---           ┆ ---    ┆ ---        │
│ str                                                                                     ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64         ┆ f64           ┆ f64    ┆ f64        │
╞═════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪═════════════╪═══════════════╪════════╪════════════╡
│ ("Qa'ik Urk'qii Akk'oj", 'Selenite Augmenter', "Operative's Cosmic Symmetry Augmenter") ┆ 0.0      ┆ 0.31                ┆ 1.26                  ┆ … ┆ 0.0         ┆ 0.0           ┆ 0.0    ┆ 782.856064 │
└─────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴─────────────┴───────────────┴────────┴────────────┘

In [34]:
a1 = "'Selenite Augmenter'"
a2 = "'Luminous Resplendent Fluxion Augmenter'"
a3 = "'Ultimate Art of Destruction Augmenter'"

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000):
    display(augs.filter(
        # augs[''].str.contains("Art of Destruction Augmenter, Ultimate") & augs[''].str.contains("Zarkara")
        pl.col("").str.contains(f"{a1}, {a2}, {a3}") | \
        pl.col("").str.contains(f"{a2}, {a1}, {a3}") | \
        pl.col("").str.contains(f"{a2}, {a3}, {a1}") | \
        pl.col("").str.contains(f"{a3}, {a2}, {a1}") | \
        pl.col("").str.contains(f"{a1}, {a3}, {a2}") | \
        pl.col("").str.contains(f"{a3}, {a1}, {a2}")
    ))

shape: (1, 31)
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬─────────────┬───────────────┬────────┬──────────┐
│                                                                                                           ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Weapon Hold ┆ Weapons Slots ┆ Weight ┆ dps      │
│ ---                                                                                                       ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---         ┆ ---           ┆ ---    ┆ ---      │
│ str                                                                                                       ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64         ┆ f64           ┆ f64    ┆ f64      │
╞═══════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪═════════════╪═══════════════╪════════╪══════════╡
│ ('Selenite Augmenter', 'Ultimate Art of Destruction Augmenter', 'Luminous Resplendent Fluxion Augmenter') ┆ 0.13     ┆ 0.12                ┆ 0.0                   ┆ … ┆ 0.5         ┆ 0.02          ┆ 0.0    ┆ 740.5125 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴─────────────┴───────────────┴────────┴──────────┘

In [11]:
tmp = augs.filter(
    pl.col("dps") >= 650,
    pl.col("Resistance to Damage") >= 0.5,
    pl.col("Shield Max") >= 1.8,
    pl.col("Range") > 0,
    pl.col("Electric Tempering") < 0.0,
    pl.col("Energy Max") > 0.5,
    # pl.col("Energy Charge") > 0.5
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
)

with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=50):
    display(tmp.sort("dps", descending=True))

shape: (36, 20)
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┬─────────────────────┬───────────────────────┬───┬────────────────────┬───────────┬────────┬────────────┐
│                                                                                                                                    ┆ Capacity  ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Transference Power ┆ Turning   ┆ Weight ┆ dps        │
│ ---                                                                                                                                ┆ ---       ┆ ---                 ┆ ---                   ┆   ┆ ---                ┆ ---       ┆ ---    ┆ ---        │
│ str                                                                                                                                ┆ f64       ┆ f64                 ┆ f64                   ┆   ┆ f64                ┆ f64       ┆ f64    ┆ f64        │
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════╪═════════════════════╪═══════════════════════╪═══╪════════════════════╪═══════════╪════════╪════════════╡
│ ("Qa'ik Vazuk Akk'oj", 'Ultimate Art of Destruction Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                         ┆ 0.0       ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 913.185    │
│ ("Nightfury's Anger", 'Celestial Nebulae Augmenter', 'Eclipse Augmenter')                                                          ┆ -0.140704 ┆ 0.2                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ -0.33     ┆ 0.0    ┆ 896.4      │
│ ("Nightfury's Anger", 'Ultimate Art of Destruction Augmenter', 'Celestial Rage Augmenter')                                         ┆ -0.1      ┆ 0.2                 ┆ 0.8                   ┆ … ┆ 0.0                ┆ -0.33     ┆ 0.0    ┆ 776.95625  │
│ ("Nightfury's Anger", 'Ultimate Art of Destruction Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                          ┆ -0.1      ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ -0.33     ┆ 2.0    ┆ 772.695    │
│ ("Kidd's Modification", 'Luminous Intersticial Desistance Augmenter', 'Luminous Obliterative Integrity Augmenter')                 ┆ 0.15      ┆ 0.27                ┆ 1.7                   ┆ … ┆ 0.0                ┆ 0.4       ┆ 0.0    ┆ 772.24896  │
│ ("Kidd's Modification", "Qa'ik Vazuk Akk'oj", 'Ultimate Art of Destruction Augmenter')                                             ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.4       ┆ 0.0    ┆ 749.275    │
│ ("Kidd's Modification", "Qa'ik Vazuk Akk'oj", 'Luminous Brace Levee Augmenter')                                                    ┆ 0.0       ┆ 0.14                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.4       ┆ 0.0    ┆ 748.9352   │
│ ("Kidd's Modification", 'Luminous Obliterative Integrity Augmenter', "Operative's Accurized Conduits Augmenter")                   ┆ 0.0       ┆ 0.07                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.4       ┆ 0.0    ┆ 743.36512  │
│ ('Perilous Augmenter', 'Celestial Nebulae Augmenter', 'Luminous Resplendent Fluxion Augmenter')                                    ┆ 0.13      ┆ 0.32                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 726.10875  │
│ ('Raging Dionysis Augmenter', 'Ultimate Art of Destruction Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                  ┆ 0.0       ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ -0.1      ┆ 2.0    ┆ 725.865    │
│ ('Empyreal Estelle Augmenter', 'Luminous Resplendent Fluxion Augmenter', 'Luminous Obliterative Integrity Augmenter')              ┆ 0.13      ┆ 0.19                ┆ 0.7                   ┆ … ┆ 0.0                ┆ -0.1      ┆ -0.5   ┆ 724.78392  │
│ ("Nightfury's Patience", 'Celestial Nebulae Augmenter', 'Luminous Intersticial Desistance Augmenter')                              ┆ 0.038889  ┆ 0.4                 ┆ 1.0                   ┆ … ┆ 0.0                ┆ -0.33     ┆ 0.0    ┆ 717.025    │
│ ('Ultimate Art of Destruction Augmenter', 'Celeste Mark Augmenter', 'Celestial Rage Augmenter')                                    ┆ 0.0       ┆ 0.2                 ┆ 1.1                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 715.8375   │
│ ("Nightfury's Anger", "Qa'ik Urk'qii Akk'oj", 'Ultimate Art of Destruction Augmenter')                                             ┆ -0.1      ┆ 0.2                 ┆ 0.6                   ┆ … ┆ 0.0                ┆ -0.33     ┆ 0.0    ┆ 712.8      │
│ ('Selenite Augmenter', 'Ultimate Art of Destruction Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                         ┆ 0.0       ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 710.255    │
│ ('Ultimate Art of Destruction Augmenter', 'Deimos Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                           ┆ 0.0       ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 710.255    │
│ ('Perilous Augmenter', 'Twisted Tesla Augmenter', 'Celestial Nebulae Augmenter')                                                   ┆ 0.0       ┆ 0.3                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 705.0      │
│ ('Perilous Augmenter', 'Celestial Rage Augmenter', 'Total Eclipse Illunis Augmenter')                                              ┆ 0.0       ┆ 0.3                 ┆ 2.15                  ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 703.104063 │
│ ('Perilous Augmenter', 'Ultimate Art of Destruction Augmenter', 'Luminous Obliterative Integrity Augmenter')                       ┆ 0.0       ┆ 0.07                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 701.40096  │
│ ("Nightfury's Patience", 'Celestial Nebulae Augmenter', "Operative's Accurized Conduits Augmenter")                                ┆ -0.1      ┆ 0.2                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ -0.33     ┆ 0.0    ┆ 700.3125   │
│ ('Ultimate Art of Destruction Augmenter', 'Celeste Mark Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                     ┆ 0.0       ┆ 0.18                ┆ 0.3                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 694.87275  │
│ ('Lunarian Augmenter', 'Celestial Nebulae Augmenter', 'Empyreal Inharmony Augmenter')                                              ┆ 0.0       ┆ 0.2                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 678.6      │
│ ('Celestial Nebulae Augmenter', 'Luminous Intersticial Desistance Augmenter', 'Lustrous Unalloyed Promontory Augmenter')           ┆ 0.15      ┆ 0.58                ┆ 1.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 672.375    │
│ ('Empyreal Inharmony Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Luminous Ostentatious Prestige Augmenter')          ┆ 0.0       ┆ 0.07                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 670.03804  │
│ ('Molten Fires of Hephaestus+ Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Luminous Ostentatious Prestige Augmenter') ┆ 0.45      ┆ 0.07                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 667.18386  │
│ ('Celestial Nebulae Augmenter', 'Empyreal Inharmony Augmenter', 'Luminous Munitions Amplifier Augmenter')                          ┆ 0.1       ┆ 0.2                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 663.17625  │
│ ("Kidd's Modification", "Nightfury's Anger", 'Ultimate Art of Destruction Augmenter')                                              ┆ -0.1      ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ -0.084699 ┆ 0.0    ┆ 661.125    │
│ ('Lunarian Augmenter', 'Empyreal Inharmony Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                                  ┆ 0.0       ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 660.303    │
│ ("Kidd's Modification", 'Zarkara Sattva', "Operative's Accurized Conduits Augmenter")                                              ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.8       ┆ 0.0    ┆ 657.23     │
│ ('Ultimate Art of Destruction Augmenter', 'Zarkara Sattva', 'Luminous Ostentatious Prestige Augmenter')                            ┆ 0.0       ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.4       ┆ 0.0    ┆ 656.5125   │
│ ('Perilous Augmenter', 'Molten Fires of Hephaestus+ Augmenter', 'Empyreal Rage Augmenter')                                         ┆ 0.45      ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 656.0      │
│ ('Celestial Forge Augmenter', 'Empyreal Rage Augmenter', 'Luminous Brace Levee Augmenter')                                         ┆ 0.0       ┆ 0.14                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.2       ┆ 0.0    ┆ 655.43445  │
│ ('Ultimate Art of Destruction Augmenter', 'Celestial Focus Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                  ┆ 0.1       ┆ 0.18                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 2.0    ┆ 655.368819 │
│ ('Perilous Augmenter', 'Molten Fires of Hephaestus+ Augmenter', 'Adamanturized Rage Augmenter')                                    ┆ 0.45      ┆ 0.0                 ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 654.71875  │
│ ('Ultimate Art of Destruction Augmenter', 'Empyreal Inharmony Augmenter', 'Luminous Obliterative Integrity Augmenter')             ┆ 0.0       ┆ 0.07                ┆ 0.7                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 654.49984  │
│ ('Perilous Augmenter', 'Luminous Resplendent Fluxion Augmenter', 'Luminous Ostentatious Prestige Augmenter')                       ┆ 0.13      ┆ 0.12                ┆ 0.0                   ┆ … ┆ 0.0                ┆ 0.0       ┆ 0.0    ┆ 650.18625  │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┴─────────────────────┴───────────────────────┴───┴────────────────────┴───────────┴────────┴────────────┘