In [2]:
import numpy as np
import polars as pl

In [3]:
augs = pl.read_csv("parsed_augmenters.csv").drop(
    "Tech"
).with_columns(
    pl.exclude("Name").cast(pl.Float64)
)

In [4]:
augs.filter(
    pl.col("Name").is_in([
        "Ult. Obliteration Augmenter",
        "Nightfury's Patience"
    ])
)

shape: (2, 30)
┌──────────────┬──────────┬──────────────┬──────────┬───┬──────────────┬────────┬─────────┬────────┐
│ Name         ┆ Capacity ┆ Critical Hit ┆ Critical ┆ … ┆ Visibility   ┆ Weapon ┆ Weapons ┆ Weight │
│ ---          ┆ ---      ┆ Chance       ┆ Hit      ┆   ┆ ---          ┆ Hold   ┆ Slots   ┆ ---    │
│ str          ┆ f64      ┆ ---          ┆ Strength ┆   ┆ f64          ┆ ---    ┆ ---     ┆ f64    │
│              ┆          ┆ f64          ┆ ---      ┆   ┆              ┆ f64    ┆ f64     ┆        │
│              ┆          ┆              ┆ f64      ┆   ┆              ┆        ┆         ┆        │
╞══════════════╪══════════╪══════════════╪══════════╪═══╪══════════════╪════════╪═════════╪════════╡
│ Ult.         ┆ null     ┆ null         ┆ 1.0      ┆ … ┆ null         ┆ null   ┆ null    ┆ null   │
│ Obliteration ┆          ┆              ┆          ┆   ┆              ┆        ┆         ┆        │
│ Augmenter    ┆          ┆              ┆          ┆   ┆              ┆        ┆         ┆        │
│ Nightfury's  ┆ -0.1     ┆ null         ┆ null     ┆ … ┆ 2.0          ┆ null   ┆ null    ┆ null   │
│ Patience     ┆          ┆              ┆          ┆   ┆              ┆        ┆         ┆        │
└──────────────┴──────────┴──────────────┴──────────┴───┴──────────────┴────────┴─────────┴────────┘

In [15]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "The Emperor's Augmenter",
        "Ult. Obliteration Augmenter",
        "Qa'ik Vazuk Akk'oj"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬─────────────────┬────────────────┬────────┬───┬────────┬─────────┬────────┬───────────┐
│ Capacity ┆ Critical Hit    ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps       │
│ ---      ┆ Chance          ┆ Strength       ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---       │
│ f64      ┆ ---             ┆ ---            ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64       │
│          ┆ f64             ┆ f64            ┆        ┆   ┆ f64    ┆ f64     ┆        ┆           │
╞══════════╪═════════════════╪════════════════╪════════╪═══╪════════╪═════════╪════════╪═══════════╡
│ 0.0      ┆ 0.1             ┆ 1.0            ┆ 1.55   ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 1011.7125 │
└──────────┴─────────────────┴────────────────┴────────┴───┴────────┴─────────┴────────┴───────────┘

In [14]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Celeste Mark Augmenter",
        "Raurava Bhava",
        "Qa'ik Urk'qii Akk'oj"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬────────────────┬────────────────┬────────┬───┬────────┬─────────┬────────┬────────────┐
│ Capacity ┆ Critical Hit   ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps        │
│ ---      ┆ Chance         ┆ Strength       ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---        │
│ f64      ┆ ---            ┆ ---            ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64        │
│          ┆ f64            ┆ f64            ┆        ┆   ┆ f64    ┆ f64     ┆        ┆            │
╞══════════╪════════════════╪════════════════╪════════╪═══╪════════╪═════════╪════════╪════════════╡
│ 0.0      ┆ 0.2            ┆ 0.9            ┆ 2.2    ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 389.508197 │
└──────────┴────────────────┴────────────────┴────────┴───┴────────┴─────────┴────────┴────────────┘