In [1]:
import numpy as np
import polars as pl

In [2]:
augs = pl.read_csv("parsed_augmenters.csv").drop(
    "Tech"
).with_columns(
    pl.exclude("Name").cast(pl.Float64)
)

In [3]:
augs.filter(pl.col("Name").is_in(["Luminous Intersticial Desistance Augmenter"]))

shape: (1, 30)
┌──────────────┬──────────┬──────────────┬──────────┬───┬──────────────┬────────┬─────────┬────────┐
│ Name         ┆ Capacity ┆ Critical Hit ┆ Critical ┆ … ┆ Visibility   ┆ Weapon ┆ Weapons ┆ Weight │
│ ---          ┆ ---      ┆ Chance       ┆ Hit      ┆   ┆ ---          ┆ Hold   ┆ Slots   ┆ ---    │
│ str          ┆ f64      ┆ ---          ┆ Strength ┆   ┆ f64          ┆ ---    ┆ ---     ┆ f64    │
│              ┆          ┆ f64          ┆ ---      ┆   ┆              ┆ f64    ┆ f64     ┆        │
│              ┆          ┆              ┆ f64      ┆   ┆              ┆        ┆         ┆        │
╞══════════════╪══════════╪══════════════╪══════════╪═══╪══════════════╪════════╪═════════╪════════╡
│ Luminous     ┆ 0.15     ┆ 0.2          ┆ 1.0      ┆ … ┆ null         ┆ null   ┆ -0.01   ┆ null   │
│ Intersticial ┆          ┆              ┆          ┆   ┆              ┆        ┆         ┆        │
│ Desistan…    ┆          ┆              ┆          ┆   ┆              ┆        ┆         ┆        │
└──────────────┴──────────┴──────────────┴──────────┴───┴──────────────┴────────┴─────────┴────────┘

In [7]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.filter(
    pl.col("Name").is_in([
        "Qa'ik Urk'qii Akk'oj",
    ])
).select(
    pl.all().repeat_by(2).flatten()
).vstack(
    augs.filter(pl.col("Name") == "Luminous Intersticial Desistance Augmenter")
    # augs.filter(pl.col("Name") == "Conclusion Augmenter")
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength"))))),
    dph=(100 * (1 + pl.col("Damage"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

shape: (1, 31)
┌──────────┬────────────────┬────────────────┬────────┬───┬───────────────┬────────┬───────┬───────┐
│ Capacity ┆ Critical Hit   ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapons Slots ┆ Weight ┆ dps   ┆ dph   │
│ ---      ┆ Chance         ┆ Strength       ┆ ---    ┆   ┆ ---           ┆ ---    ┆ ---   ┆ ---   │
│ f64      ┆ ---            ┆ ---            ┆ f64    ┆   ┆ f64           ┆ f64    ┆ f64   ┆ f64   │
│          ┆ f64            ┆ f64            ┆        ┆   ┆               ┆        ┆       ┆       │
╞══════════╪════════════════╪════════════════╪════════╪═══╪═══════════════╪════════╪═══════╪═══════╡
│ 0.15     ┆ 0.6            ┆ 2.2            ┆ 1.35   ┆ … ┆ -0.01         ┆ 0.0    ┆ 479.4 ┆ 479.4 │
└──────────┴────────────────┴────────────────┴────────┴───┴───────────────┴────────┴───────┴───────┘

In [8]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.filter(
    pl.col("Name").is_in([
        "Luminous Intersticial Desistance Augmenter"
    ])
).select(
    pl.all().repeat_by(2).flatten()
).vstack(
    # augs.filter(pl.col("Name") == "Luminous Intersticial Desistance Augmenter")
    augs.filter(pl.col("Name") == "Qa'ik Urk'qii Akk'oj")
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength"))))),
    dph=(100 * (1 + pl.col("Damage"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

shape: (1, 31)
┌──────────┬───────────────┬───────────────┬────────┬───┬───────────────┬────────┬────────┬────────┐
│ Capacity ┆ Critical Hit  ┆ Critical Hit  ┆ Damage ┆ … ┆ Weapons Slots ┆ Weight ┆ dps    ┆ dph    │
│ ---      ┆ Chance        ┆ Strength      ┆ ---    ┆   ┆ ---           ┆ ---    ┆ ---    ┆ ---    │
│ f64      ┆ ---           ┆ ---           ┆ f64    ┆   ┆ f64           ┆ f64    ┆ f64    ┆ f64    │
│          ┆ f64           ┆ f64           ┆        ┆   ┆               ┆        ┆        ┆        │
╞══════════╪═══════════════╪═══════════════╪════════╪═══╪═══════════════╪════════╪════════╪════════╡
│ 0.3      ┆ 0.6           ┆ 2.6           ┆ 1.05   ┆ … ┆ -0.019802     ┆ 0.0    ┆ 444.85 ┆ 444.85 │
└──────────┴───────────────┴───────────────┴────────┴───┴───────────────┴────────┴────────┴────────┘

In [14]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Celeste Mark Augmenter",
        "Qa'ik Urk'qii Akk'oj",
        "Raurava Bhava"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬────────────────┬────────────────┬────────┬───┬────────┬─────────┬────────┬────────────┐
│ Capacity ┆ Critical Hit   ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps        │
│ ---      ┆ Chance         ┆ Strength       ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---        │
│ f64      ┆ ---            ┆ ---            ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64        │
│          ┆ f64            ┆ f64            ┆        ┆   ┆ f64    ┆ f64     ┆        ┆            │
╞══════════╪════════════════╪════════════════╪════════╪═══╪════════╪═════════╪════════╪════════════╡
│ 0.0      ┆ 0.2            ┆ 0.9            ┆ 2.2    ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 389.508197 │
└──────────┴────────────────┴────────────────┴────────┴───┴────────┴─────────┴────────┴────────────┘

In [3]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Empyreal Rage Augmenter",
        "Twisted Tesla Augmenter",
        "Selenite Augmenter",
        "Ultimate Art of Fast Killing Augmenter"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬──────────────┬──────────────┬────────┬───┬────────┬─────────┬────────┬──────────┐
│ Capacity ┆ Critical Hit ┆ Critical Hit ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps      │
│ ---      ┆ Chance       ┆ Strength     ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---      │
│ f64      ┆ ---          ┆ ---          ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64      │
│          ┆ f64          ┆ f64          ┆        ┆   ┆ f64    ┆ f64     ┆        ┆          │
╞══════════╪══════════════╪══════════════╪════════╪═══╪════════╪═════════╪════════╪══════════╡
│ 0.0      ┆ 0.2          ┆ 0.4          ┆ 2.0    ┆ … ┆ 0.0    ┆ -0.01   ┆ 0.0    ┆ 1709.625 │
└──────────┴──────────────┴──────────────┴────────┴───┴────────┴─────────┴────────┴──────────┘

In [17]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Empyreal Rage Augmenter",
        "Ultimate Art of Fast Killing Augmenter",
        "Selenite Augmenter",
        "Ultimate Art of Fast Killing Augmenter"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬─────────────────┬────────────────┬────────┬───┬────────┬─────────┬────────┬───────────┐
│ Capacity ┆ Critical Hit    ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps       │
│ ---      ┆ Chance          ┆ Strength       ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---       │
│ f64      ┆ ---             ┆ ---            ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64       │
│          ┆ f64             ┆ f64            ┆        ┆   ┆ f64    ┆ f64     ┆        ┆           │
╞══════════╪═════════════════╪════════════════╪════════╪═══╪════════╪═════════╪════════╪═══════════╡
│ 0.0      ┆ 0.1             ┆ 0.4            ┆ 1.1    ┆ … ┆ 0.0    ┆ -0.01   ┆ 0.0    ┆ 1055.8275 │
└──────────┴─────────────────┴────────────────┴────────┴───┴────────┴─────────┴────────┴───────────┘

In [9]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Ult. Obliteration Augmenter",
        "Twisted Tesla Augmenter",
        "Selenite Augmenter",
        "Ultimate Art of Fast Killing Augmenter"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬──────────────┬──────────────┬────────┬───┬────────┬─────────┬────────┬──────────┐
│ Capacity ┆ Critical Hit ┆ Critical Hit ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps      │
│ ---      ┆ Chance       ┆ Strength     ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---      │
│ f64      ┆ ---          ┆ ---          ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64      │
│          ┆ f64          ┆ f64          ┆        ┆   ┆ f64    ┆ f64     ┆        ┆          │
╞══════════╪══════════════╪══════════════╪════════╪═══╪════════╪═════════╪════════╪══════════╡
│ 0.0      ┆ 0.2          ┆ 1.4          ┆ 1.95   ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 1361.425 │
└──────────┴──────────────┴──────────────┴────────┴───┴────────┴─────────┴────────┴──────────┘

In [6]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Ult. Obliteration Augmenter",
        "Raurava Bhava",
        "Qa'ik Urk'qii Akk'oj"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌──────────┬────────────────┬────────────────┬────────┬───┬────────┬─────────┬────────┬────────────┐
│ Capacity ┆ Critical Hit   ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps        │
│ ---      ┆ Chance         ┆ Strength       ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---        │
│ f64      ┆ ---            ┆ ---            ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64        │
│          ┆ f64            ┆ f64            ┆        ┆   ┆ f64    ┆ f64     ┆        ┆            │
╞══════════╪════════════════╪════════════════╪════════╪═══╪════════╪═════════╪════════╪════════════╡
│ 0.0      ┆ 0.2            ┆ 1.6            ┆ 2.1    ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 367.835821 │
└──────────┴────────────────┴────────────────┴────────┴───┴────────┴─────────┴────────┴────────────┘

In [16]:
augs.fill_null(0.0).with_columns(
        dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
    ).filter(
        pl.col("Electric Tempering") <= 0,
        # pl.col("Damage") >= 0.6,
        # pl.col("Rate of Fire") >= 1.0
        pl.col("dps") >= 460
    )

shape: (2, 31)
┌───────────────┬──────────┬──────────────┬──────────────┬───┬────────┬─────────┬────────┬─────────┐
│ Name          ┆ Capacity ┆ Critical Hit ┆ Critical Hit ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps     │
│ ---           ┆ ---      ┆ Chance       ┆ Strength     ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---     │
│ str           ┆ f64      ┆ ---          ┆ ---          ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64     │
│               ┆          ┆ f64          ┆ f64          ┆   ┆ f64    ┆ f64     ┆        ┆         │
╞═══════════════╪══════════╪══════════════╪══════════════╪═══╪════════╪═════════╪════════╪═════════╡
│ Empyreal Rage ┆ 0.0      ┆ 0.0          ┆ 0.0          ┆ … ┆ 0.0    ┆ -0.01   ┆ 0.0    ┆ 467.4   │
│ Augmenter     ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆         │
│ Lustrous Mass ┆ 0.0      ┆ 0.0          ┆ 0.0          ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 470.475 │
│ Despoliation  ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆         │
│ Aug…          ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆         │
└───────────────┴──────────┴──────────────┴──────────────┴───┴────────┴─────────┴────────┴─────────┘

In [7]:
args1 = (
    pl.when(pl.col(i) <= 0).then(-1 / (pl.col(i) + 1) + 1).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)
# res[res <= 0] = -1 - 1 / (res[res <= 0] - 1)
args2 = (
    pl.when(pl.col(i) <= 0).then(-1 - 1 / (pl.col(i) - 1)).otherwise(pl.col(i)).alias(i) for i in augs.columns[1:]
)

augs.lazy().filter(
    pl.col("Name").is_in([
        "Vaidya Bhava",
        "Ult. Reviving Augmenter",
        "Nightfury's Patience",
        "Qa'ik Banu Akk'oj"
    ])
).with_columns(
    *args1
).select(
    pl.exclude("Name").sum()
).with_columns(
    *args2
).with_columns(
    hps=(100 * (1 + pl.col("Transference Power")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
).collect()

shape: (1, 30)
┌───────────┬─────────────────┬────────────────┬────────┬───┬────────┬─────────┬────────┬──────────┐
│ Capacity  ┆ Critical Hit    ┆ Critical Hit   ┆ Damage ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ hps      │
│ ---       ┆ Chance          ┆ Strength       ┆ ---    ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---      │
│ f64       ┆ ---             ┆ ---            ┆ f64    ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64      │
│           ┆ f64             ┆ f64            ┆        ┆   ┆ f64    ┆ f64     ┆        ┆          │
╞═══════════╪═════════════════╪════════════════╪════════╪═══╪════════╪═════════╪════════╪══════════╡
│ -0.020675 ┆ 0.0             ┆ 0.3            ┆ 1.1    ┆ … ┆ 0.0    ┆ 0.0     ┆ 0.0    ┆ 872.4625 │
└───────────┴─────────────────┴────────────────┴────────┴───┴────────┴─────────┴────────┴──────────┘